# Generated by Django 4.2.7 on 2023-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_items_alter_cart_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='count',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
