# Generated by Django 4.2.7 on 2023-11-20 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('74fdefcc-8bfc-44f1-8179-660a4db09633'), max_length=300, verbose_name='uid'),
        ),
    ]
