# Generated by Django 4.2.7 on 2023-11-20 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('4c8b797f-0e27-4323-8f46-9f9dd95ccb30'), max_length=300, verbose_name='uid'),
        ),
    ]
