# Generated by Django 4.2.7 on 2023-11-20 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_otp_alter_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('1bc1a9b2-4b6b-41cf-8c54-94b3f3856151'), max_length=300, verbose_name='uid'),
        ),
    ]
