# Generated by Django 4.2.7 on 2023-11-21 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_otp_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('11739460-2f39-4abf-99b8-895a91788c7d'), max_length=300, verbose_name='uid'),
        ),
    ]
