# Generated by Django 4.2.7 on 2023-11-22 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('72c48959-768a-4ff3-aff2-037493433236'), max_length=300, verbose_name='uid'),
        ),
    ]
