# Generated by Django 4.2.7 on 2023-11-25 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('55ace93a-89a5-468d-ad69-50abef486e5b'), max_length=300, verbose_name='uid'),
        ),
    ]
