# Generated by Django 4.2.7 on 2023-11-26 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('db599994-d509-4865-a3fe-358da93e2ea4'), max_length=300, verbose_name='uid'),
        ),
    ]
