# Generated by Django 4.2.7 on 2023-11-26 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('2803472a-0c6a-4437-9de7-0c11da03ccb0'), max_length=300, verbose_name='uid'),
        ),
    ]
