# Generated by Django 4.2.7 on 2023-11-26 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('9defc9e3-cb9c-4fa3-ad1d-3b670277369e'), max_length=300, verbose_name='uid'),
        ),
    ]
