# Generated by Django 4.2.7 on 2023-12-08 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('69830cb6-851c-4085-84ce-18eb8768b16e'), max_length=300, verbose_name='uid'),
        ),
    ]
