# Generated by Django 4.2.7 on 2023-12-08 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('d4f577b6-18fa-42e7-b17d-88fd117d536f'), max_length=300, verbose_name='uid'),
        ),
    ]
