# Generated by Django 4.2.7 on 2023-12-08 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('d99f52c8-913a-4d13-a506-1fbf107c3a88'), max_length=300, verbose_name='uid'),
        ),
    ]
