# Generated by Django 4.2.7 on 2023-12-09 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('70e9c7e1-772a-4883-a251-103c615f101a'), max_length=300, verbose_name='uid'),
        ),
    ]
