# Generated by Django 4.2.7 on 2023-12-12 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('ab71af7e-fc8a-4d1c-8708-acfd3d33ffe7'), max_length=300, verbose_name='uid'),
        ),
    ]
