# Generated by Django 4.2.7 on 2023-12-18 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('d2e5ed8d-9b19-4b69-9280-ac9f840bc919'), max_length=300, verbose_name='uid'),
        ),
    ]
