# Generated by Django 4.2.7 on 2023-12-24 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('c0a98152-a2f0-453e-a579-a1e1a6e3113e'), max_length=300, verbose_name='uid'),
        ),
    ]
