# Generated by Django 4.2.7 on 2023-12-24 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('2172caab-3013-4603-b9b4-87e5870ef6d7'), max_length=300, verbose_name='uid'),
        ),
    ]
