# Generated by Django 4.2.7 on 2023-12-24 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('9941ed15-3b13-499e-ad9d-9cc792e8c9d5'), max_length=300, verbose_name='uid'),
        ),
    ]
