from config.settings.base import env

DEFAULT_FILE_STORAGE = "DEFAULT_FILE_STORAGE"
AWS_ACCESS_KEY_ID = "ARVAN_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "ARVAN_SECRET_ACCESS_KEY"

AWS_STORAGE_BUCKET_NAME = "ARVAN_STORAGE_BUCKET_NAME"
AWS_S3_REGION_NAME = "ARVAN_STORAGE_REGION_NAME"

AWS_S3_ENDPOINT_URL = "ARVAN_ENDPOINT_URL"

AWS_STORAGE_DEFAULT_ACL = "ARVAN_STORAGE_DEFAULT_ACL"
AWS_DEFAULT_ACL = "ARVAN_STORAGE_DEFAULT_ACL"

