from config.env import env


# DEFAULT_FILE_STORAGE = env("DEFAULT_FILE_STORAGE")
AWS_ACCESS_KEY_ID = env("ARVAN_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("ARVAN_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = "ARVAN_STORAGE_BUCKET_NAME"
AWS_S3_ENDPOINT_URL = env("ARVAN_ENDPOINT_URL")
AWS_S3_REGION_NAME = env("ARVAN_STORAGE_REGION_NAME")
AWS_STORAGE_DEFAULT_ACL = env("ARVAN_STORAGE_DEFAULT_ACL")
AWS_DEFAULT_ACL = env("ARVAN_STORAGE_DEFAULT_ACL")
